[versions]

kotlin = "2.2.20-Beta2"
compose = "1.9.0+dev2718"
agp = "8.9.2"
androidx-activityCompose = "1.10.1"
materialKolor = "2.1.1"
kotlinx-coroutines = "1.10.2"

[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
